/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "pack2master.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pack2master_pack_id, pack2master_pack_id, AUTO)


PB_BIND(pack2master_flags, pack2master_flags, AUTO)


PB_BIND(pack2master_data, pack2master_data, AUTO)



